# Handify - Gesture-controlled Spotify player.
# Copyright (C) 2024 Christopher Muntean
#
# This file is part of Handify and is licensed under the
# GNU General Public License v3.0. For details, see <https://www.gnu.org/licenses/>.

services:
  handify:
    image: chrismuntean/handify:latest  # Pull the latest image from Docker Hub
    ports:
      - "8080:8080"  # Map Flask app port to host
    devices:
      - "/dev/video0:/dev/video0"  # Allow access to the webcam
    env_file:
      - .env  # Pass the .env file